from datetime import datetime


class StrategyBase:

    def __init__(self, name,
                 broadcast_service=None,
                 notification_service=None):

        self.name = name

        self.broadcast_service = broadcast_service
        self.notification_service = notification_service

        self.active = False
        self.parameters = {}
        self.last_signal = None
        self.last_signal_time = None  # Track when last signal was generated

        print(f"🧠 Strategy Initialised → {self.name}")

    # -------------------------------------------------

    def start(self):
        self.active = True
        print(f"▶ Strategy Started → {self.name}")

        if self.notification_service:
            self.notification_service.notify_system(
                f"{self.name} strategy started"
            )

    # -------------------------------------------------

    def stop(self):
        self.active = False
        print(f"⏹ Strategy Stopped → {self.name}")

        if self.notification_service:
            self.notification_service.notify_system(
                f"{self.name} strategy stopped"
            )

    # -------------------------------------------------

    def update_parameters(self, params: dict):
        self.parameters.update(params)
        print(f"⚙ Params Updated → {self.name} → {params}")

    # -------------------------------------------------

    def generate_signal(self, signal_data):

        if not self.active:
            return

        payload = {
            "strategy": self.name,
            "signal": signal_data,
            "time": datetime.utcnow().isoformat()
        }

        self.last_signal = payload

        # ---- broadcast to websocket pipeline ----
        if self.broadcast_service:
            self.broadcast_service.broadcast_strategy_signal(
                self.name,
                payload
            )

        # ---- notify operator ----
        if self.notification_service:
            self.notification_service.notify_signal(
                payload
            )

    # -------------------------------------------------

    def get_status(self):

        return {
            "active": self.active,
            "params": self.parameters,
            "last_signal": self.last_signal
        }

    # -------------------------------------------------

    def broadcast_signal(self, signal_data):
        """
        Broadcast a signal generated by the strategy.
        This is called directly by child strategies after they generate a signal.
        """
        if not self.active:
            return
        
        # ---- broadcast to websocket pipeline ----
        if self.broadcast_service:
            self.broadcast_service.broadcast_strategy_signal(
                self.name,
                signal_data
            )
        
        # Store last signal
        self.last_signal = {
            "strategy": self.name,
            "data": signal_data,
            "time": datetime.utcnow().isoformat()
        }
        
        # ---- notify operator ----
        if self.notification_service:
            self.notification_service.notify_signal(
                self.last_signal
            )

    # -------------------------------------------------

    # ===== ABSTRACT METHOD (must override) =====
    def on_market_data(self, data):
        """
        strategy logic implemented in child classes
        """
        raise NotImplementedError

    # -------------------------------------------------

    def risk_filter(self, signal: dict):
        """
        Apply basic risk filters to signal before broadcasting.
        Override in child classes for custom risk logic.
        Returns signal if passes filters, None if rejected.
        """
        if not signal:
            return None
        
        # Basic confidence threshold filter
        confidence = signal.get("confidence", 0)
        if confidence < 0.5:
            print(f"⚠ Signal rejected - low confidence: {confidence:.2f}")
            return None
        
        # Validate required fields
        required = ["symbol", "direction", "entry_price"]
        for field in required:
            if field not in signal:
                print(f"⚠ Signal rejected - missing field: {field}")
                return None
        
        return signal